thisdir = class/System.IO.Compression
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.IO.Compression.dll
LIB_MCS_FLAGS = /r:System
TEST_MCS_FLAGS = /r:System

include ../../build/library.make
